# -*- coding: utf-8 -*-
"""milestone-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ICyNbp7TJYWDCmRuqWFXLrJcR52Qblp
"""

!pip install pandas nltk scikit-learn textblob

import pandas as pd
import re
import nltk

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from textblob import TextBlob

nltk.download('punkt')
nltk.download('stopwords')

print("Libraries imported successfully!")

print("Reading cleaned data...")

df = pd.read_csv("news_data_cleaned.csv")

print("✔ Dataset loaded successfully")
print("Total records:", len(df))
df.head()

df["news_text"] = df["Title"].fillna("") + " " + df["Description"].fillna("")

print("✔ Title and Description combined")
df[["news_text"]].head()

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

print("Text cleaning started...")

df["cleaned_news"] = df["news_text"].apply(clean_text)

print("✔ Text cleaning completed")
df[["cleaned_news"]].head()

import nltk
nltk.download('punkt_tab')

stop_words = set(stopwords.words("english"))

def tokenize_text(text):
    tokens = word_tokenize(text)
    tokens = [
        word for word in tokens
        if word.isalpha() and word not in stop_words and len(word) > 2
    ]
    return " ".join(tokens)

print("Tokenization and stopword removal started...")

df["processed_text"] = df["cleaned_news"].apply(tokenize_text)

print("✔ Tokenization and stopword removal completed")
df[["processed_text"]].head()

print("Applying TF-IDF feature extraction...")

vectorizer = TfidfVectorizer(max_features=1000)
tfidf_matrix = vectorizer.fit_transform(df["processed_text"])

feature_names = vectorizer.get_feature_names_out()
mean_scores = tfidf_matrix.toarray().mean(axis=0)

top_indices = mean_scores.argsort()[-10:][::-1]
top_keywords = [feature_names[i] for i in top_indices]

print("✔ Top 10 keywords extracted:")
for word in top_keywords:
    print("-", word)

print("Applying topic modeling (LDA)...")

lda = LatentDirichletAllocation(n_components=3, random_state=42)
lda.fit(tfidf_matrix)

topics = []
for idx, topic in enumerate(lda.components_):
    words = [feature_names[i] for i in topic.argsort()[-10:]]
    topic_words = ", ".join(words)
    topics.append(topic_words)
    print(f"Topic {idx+1} → {topic_words}")

print("✔ Topic modeling completed")

print("Applying sentiment analysis...")

def get_sentiment(text):
    polarity = TextBlob(text).sentiment.polarity
    if polarity > 0:
        return "Positive"
    elif polarity < 0:
        return "Negative"
    else:
        return "Neutral"

df["sentiment"] = df["processed_text"].apply(get_sentiment)

print("✔ Sentiment analysis completed")

print("Sentiment Distribution:")
sentiment_counts = df["sentiment"].value_counts()
print(sentiment_counts)

df.to_csv("news_with_sentiment.csv", index=False)

print("✔ Final file saved: news_with_sentiment.csv")

print("\n========================================")
print("🎉 MILESTONE 2 COMPLETED SUCCESSFULLY 🎉")
print("========================================")